version: "3.9"

services:
  backend:
    build: .
    image: audiobyte
    ports:
      - 4000:4000
    command: python run.py
    container_name: audiobyte_app
    volumes:
      - backend_logs:/data
    depends_on:
      - redis
    networks:
      - audiobyte_network
    restart: always

  redis:
    image: "redis:latest"
    container_name: audiobyte_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - audiobyte_network
    restart: always

volumes:
  redis_data:
  backend_logs:
  restart_script:
    driver: local

networks:
  audiobyte_network:
    name: audiobyte_network
    driver: bridge
